name: Release stud.phar

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to build (e.g. 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: box

      - name: Get app name and version
        id: get_version
        run: |
          APP_NAME="stud"
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            APP_VERSION="${{ github.event.inputs.version }}"
          else
            APP_VERSION=$(jq -r .version composer.json)
          fi
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "PHAR_FILENAME=${APP_NAME}-${APP_VERSION}.phar" >> $GITHUB_ENV

      - name: Build and rename phar
        run: |
          composer install --no-dev

          vendor/bin/castor repack \
            --logo-file src/repack/logo.php \
            --app-name "${{ env.APP_NAME }}" \
            --app-version "${{ env.APP_VERSION }}"
          mv "${{ env.APP_NAME }}.linux.phar" "${{ env.PHAR_FILENAME }}"

      - name: Create Release and Upload Phar
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PHAR_FILENAME }}

      - name: Upload artifact (dry-run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PHAR_FILENAME }}
          path: ${{ env.PHAR_FILENAME }}
          retention-days: 1